# Exported from Render on 2025-09-20T07:18:16Z
version: "1"
services:
- type: web
  name: portfolio-backend
  runtime: docker
  repo: https://github.com/sourabh-git-dev/portfolio-backend
  plan: free
  envVars:
  - key: SENDGRID_FROM_EMAIL
    sync: false
  - key: SENDGRID_API_KEY
    sync: false
  - key: DB_PASS
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
